### ISSUE TITLE
Pretrain code for Electra

### ISSUE THREAD

**Issue by Taekyoon** [lassl/lassl#21]
### Todos 

- [ ] 1. Electra Configs 생성 
- [ ] 2. Electra Dataset 구현
- [ ] 3. Electra Runner 구현
- [ ] 4. Tokenizer & Serialize Test
- [ ] 5. Pretraining Test
